// <auto-generated />
using System;
using AttendanceMonitoring;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceMonitoring.Migrations
{
    [DbContext(typeof(AttendanceMonitoringContext))]
    [Migration("20251011133842_v1.3")]
    partial class v13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AttendanceMonitoring.Models.Advisory", b =>
                {
                    b.Property<string>("AdvisoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassAdviserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdvisoryId");

                    b.HasIndex("ClassAdviserId");

                    b.HasIndex("StudentId");

                    b.ToTable("Advisory", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Attendance", b =>
                {
                    b.Property<string>("AttendanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Class_Adviser", b =>
                {
                    b.Property<string>("ClassAdviserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ClassAdviserId");

                    b.ToTable("Class_Adviser", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Contact", b =>
                {
                    b.Property<string>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ContactId");

                    b.HasIndex("ParentId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Delivered", b =>
                {
                    b.Property<string>("DeliveredId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeSent")
                        .HasColumnType("date");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeliveredId");

                    b.HasIndex("ContactId");

                    b.HasIndex("NotificationId");

                    b.ToTable("Delivered", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.HasKey("NotificationId");

                    b.HasIndex("AttendanceId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Parent", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ParentId");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Relationship", b =>
                {
                    b.Property<string>("RelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RelationshipId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Relationship", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentStatus")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LRN")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Advisory", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Class_Adviser", "ClassAdviserLink")
                        .WithMany("AdvisoryList")
                        .HasForeignKey("ClassAdviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("AdvisoryList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassAdviserLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Attendance", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("AttendanceList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Contact", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Parent", "ParentLink")
                        .WithMany("ContactList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Delivered", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Contact", "ContactLink")
                        .WithMany("DeliveredList")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceMonitoring.Models.Notification", "NotificationLink")
                        .WithMany("DeliveredList")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactLink");

                    b.Navigation("NotificationLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Notification", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Attendance", "AttendanceLink")
                        .WithMany("NotificationList")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Relationship", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Parent", "ParentLink")
                        .WithMany("RelationshipList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("RelationshipList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Attendance", b =>
                {
                    b.Navigation("NotificationList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Class_Adviser", b =>
                {
                    b.Navigation("AdvisoryList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Contact", b =>
                {
                    b.Navigation("DeliveredList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Notification", b =>
                {
                    b.Navigation("DeliveredList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Parent", b =>
                {
                    b.Navigation("ContactList");

                    b.Navigation("RelationshipList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Student", b =>
                {
                    b.Navigation("AdvisoryList");

                    b.Navigation("AttendanceList");

                    b.Navigation("RelationshipList");
                });
#pragma warning restore 612, 618
        }
    }
}
