// <auto-generated />
using System;
using AttendanceMonitoring;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceMonitoring.Migrations
{
    [DbContext(typeof(AttendanceMonitoringContext))]
    [Migration("20260111051905_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AttendanceMonitoring.Models.Advisory", b =>
                {
                    b.Property<int>("AdvisoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassAdviserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdvisoryId");

                    b.HasIndex("ClassAdviserId");

                    b.HasIndex("StudentId");

                    b.ToTable("Advisory", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Class_Adviser", b =>
                {
                    b.Property<int>("ClassAdviserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ClassAdviserId");

                    b.ToTable("Class_Adviser", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ContactId");

                    b.HasIndex("ParentId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ParentId");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Relationship", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelationshipId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Relationship", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnrollmentStatus")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LRN")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RFID")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Advisory", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Class_Adviser", "ClassAdviserLink")
                        .WithMany("AdvisoryList")
                        .HasForeignKey("ClassAdviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("AdvisoryList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassAdviserLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Attendance", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("AttendanceList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Contact", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Parent", "ParentLink")
                        .WithMany("ContactList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Relationship", b =>
                {
                    b.HasOne("AttendanceMonitoring.Models.Parent", "ParentLink")
                        .WithMany("RelationshipList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceMonitoring.Models.Student", "StudentLink")
                        .WithMany("RelationshipList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Class_Adviser", b =>
                {
                    b.Navigation("AdvisoryList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Parent", b =>
                {
                    b.Navigation("ContactList");

                    b.Navigation("RelationshipList");
                });

            modelBuilder.Entity("AttendanceMonitoring.Models.Student", b =>
                {
                    b.Navigation("AdvisoryList");

                    b.Navigation("AttendanceList");

                    b.Navigation("RelationshipList");
                });
#pragma warning restore 612, 618
        }
    }
}
